In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 이거저거 해보기

In [3]:
df = pd.read_csv('nyc_subway_weather.csv')
df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week  ...  pressurei rain  \
0            0.0  2011-05-01 00:00:00     0         6  ...      30.22    0   
1            0.0  2011-05-01 04:00:00     4         6  ...      30.25    0   
2            0.0  2011-05-01 12:00:00    12         6  ...      30.28    0   
3            0.0  2011-05-01 16:00:00    16         6  ...      30.26    0   
4            0.0  2011-05-01 20:00:00    20         6  ...      30.28    0   

   tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  weather_lat  \
0   55.9    3.5         0.0         30.258      55.98       7.86    40.700348   
1   52.0    3.5         0.0         30.258      55.98       7.86    40.700348   
2   62.1    6.9         0.0         30.258      55.98       7.86    40.700348   
3   57.9   15.0         0.0         30.258      55.98       7.86    40.700348   
4   52.0   10.4         0.0         30.258      55.98       7.86    40.700348   

   weather_lon  
0   -73.887177  
1   -73.887177  
2   -73.887177  
3   -73.887177  
4   -73.887177  

[5 rows x 27 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42649 entries, 0 to 42648
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   UNIT             42649 non-null  object 
 1   DATEn            42649 non-null  object 
 2   TIMEn            42649 non-null  object 
 3   ENTRIESn         42649 non-null  int64  
 4   EXITSn           42649 non-null  int64  
 5   ENTRIESn_hourly  42649 non-null  float64
 6   EXITSn_hourly    42649 non-null  float64
 7   datetime         42649 non-null  object 
 8   hour             42649 non-null  int64  
 9   day_week         42649 non-null  int64  
 10  weekday          42649 non-null  int64  
 11  station          42649 non-null  object 
 12  latitude         42649 non-null  float64
 13  longitude        42649 non-null  float64
 14  conds            42649 non-null  object 
 15  fog              42649 non-null  int64  
 16  precipi          42649 non-null  float64
 17  pressurei   

In [5]:
df.iloc[:5, :10]

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week  
0            0.0  2011-05-01 00:00:00     0         6  
1            0.0  2011-05-01 04:00:00     4         6  
2            0.0  2011-05-01 12:00:00    12         6  
3            0.0  2011-05-01 16:00:00    16         6  
4            0.0  2011-05-01 20:00:00    20         6

In [6]:
df.conds.value_counts()

Clear               13594
Overcast            11975
Mostly Cloudy        6491
Scattered Clouds     3489
Partly Cloudy        2220
Light Rain           1880
Haze                 1345
Rain                  961
Light Drizzle         335
Heavy Rain            288
Fog                    47
Mist                   24
Name: conds, dtype: int64

In [30]:
from pandas_profiling import profile_report
pr = df.profile_report()
pr.to_file('nyc_subway_weather_profile.html')

## 정리..?

In [15]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([1, 2, 3])
print(array1)
print('-----')
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[1 2 3]


### 벡터 연산

In [16]:
print(array1 + array2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [17]:
print(array1 * array2)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [18]:
print(array1 ** array2)

[[  1   4  27]
 [  4  25 216]
 [  7  64 729]]


In [22]:
# 참고 : 행렬 연산
np.matmul(array1, array1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [27]:
# 참고2
print(array1.mean(), array1.std(), array1.sum())

5.0 2.7386127875258306 45


### 축 axis

In [28]:
print(array1.mean(axis=0))
print(array1.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


In [29]:
print(array1.sum(axis=0))
print(array1.sum(axis=1))

[12 15 18]
[ 6 15 24]
